### ISSUE TITLE
RFE: require podman

### ISSUE THREAD

**Issue by RadekBiba** [RedHatInsights/rhproxy#13]
One of the steps in installing the Insights Proxy is `podman login quay.io`. This can only work if podman is installed on the machine. Moreover, if a user skips this step and proceeds to `rhproxy install`, this command will appear to work but rhproxy won't be usable; systemd wouldn't actually know the service, and the next command from the procedure would fail:

```
$ rhproxy start
Starting the Insights Proxy service ...
Failed to start rhproxy.service: Unit rhproxy.service not found.
```

Would you please add podman to the list of requirements in the rhproxy spec file?

**Comment by abellotti** [comment]
This is now resolved in the 1.3.4 build of the RPM.

- https://copr.fedorainfracloud.org/coprs/g/rhproxy/rhproxy/builds
